
// This file has been generated by the GUI designer. Do not modify.
namespace vocab
{
	public partial class PlaceHolderWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget vocab.PlaceHolderWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "vocab.PlaceHolderWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
