
// This file has been generated by the GUI designer. Do not modify.
namespace vocab
{
	public partial class SimpleAssessmentWidget
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action closeAction;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.HPaned hpaned1;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox3;

		private global::vocab.PlaceHolderWidget placeholderwidget2;

		private global::Gtk.VButtonBox vbuttonbox1;

		private global::vocab.PlaceHolderWidget placeholderwidget1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget vocab.SimpleAssessmentWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.closeAction = new global::Gtk.Action ("closeAction", null, null, "gtk-close");
			w2.Add (this.closeAction, null);
			this.UIManager.InsertActionGroup (w2, 0);
			this.Name = "vocab.SimpleAssessmentWidget";
			// Container child vocab.SimpleAssessmentWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='closeAction' action='closeAction'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.vbox2.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.toolbar1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 126;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hpaned1.Add (this.label1);
			global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1[this.label1]));
			w4.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.placeholderwidget2 = new global::vocab.PlaceHolderWidget ();
			this.placeholderwidget2.Events = ((global::Gdk.EventMask)(256));
			this.placeholderwidget2.Name = "placeholderwidget2";
			this.vbox3.Add (this.placeholderwidget2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.placeholderwidget2]));
			w5.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.Homogeneous = true;
			this.vbuttonbox1.BorderWidth = ((uint)(18));
			this.vbox3.Add (this.vbuttonbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbuttonbox1]));
			w6.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.placeholderwidget1 = new global::vocab.PlaceHolderWidget ();
			this.placeholderwidget1.Events = ((global::Gdk.EventMask)(256));
			this.placeholderwidget1.Name = "placeholderwidget1";
			this.vbox3.Add (this.placeholderwidget1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.placeholderwidget1]));
			w7.Position = 2;
			w7.Padding = ((uint)(16));
			this.hpaned1.Add (this.vbox3);
			this.vbox2.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hpaned1]));
			w9.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
			this.closeAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		}
	}
}
